trigger:
  - feat/generic-webhook

resources:
  repositories:
  - repository: templatesRepo
    type: git
    name: Stater/devops-pipelines

jobs:
- template: /pipelines/jobs/docker-image.yml@templatesRepo
  parameters:
    tag: "v0.3.10-$(Build.BuildId)"
