trigger:
  - feat/generic-webhook

resources:
  repositories:
  - repository: templatesRepo
    type: git
    name: Stater/devops-pipelines

jobs:
- template: /jobs/build/docker-image.yml@templatesRepo
  parameters:
    tag: "v0.3.10-$(Build.BuildId)"
    buildArgs: "--build-arg GOPROXY=https://pr-art.europe.stater.corp/artifactory/proxy.golang.org"
