trigger:
  branches:
    include:
    - feat/generic-webhook
  tags:
    include:
    - 'v*'

resources:
  repositories:
  - repository: templatesRepo
    type: git
    name: Stater/devops-pipelines

jobs:
- template: /jobs/build/docker-image.yml@templatesRepo
  parameters:
    ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/v') }}:
      tag: ${{ replace(variables['Build.SourceBranch'], 'refs/tags/', '') }}
    ${{ else }}:
      tag: "v0.3.10-$(Build.BuildId)"
    buildArgs: "--build-arg GOPROXY=http://pr-art.europe.stater.corp/artifactory/proxy.golang.org"
- ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/v') }}:
  - job: Helm_Package
    container: stater/golang-helm:1.17
    pool: "Docker Linux"
    displayName: Helm Package
    variables:
    - group: DevOps.Pipeline.Credentials.HelmPush
    - name: appVersion
      value: ${{ replace(variables['Build.SourceBranch'], 'refs/tags/', '') }}
    - name: chartVersion
      value: ${{ replace(variables['Build.SourceBranch'], 'refs/tags/v', '') }}
    - name: chartName
      value: external-secrets
    steps:
    - script: |
        set -ex
        GOPROXY=http://pr-art.europe.stater.corp/artifactory/proxy.golang.org make generate
        for i in deploy/crds/*.yaml; do
                sed -e'1i{{- if .Values.installCRDs }}' -e'$a{{- end }}' "$i" > "deploy/charts/external-secrets/templates/crds/$(basename -- $i)"
        done
        helm package deploy/charts/external-secrets --app-version '$(appVersion)' --version '$(chartVersion)'
      displayName: Package Chart
    - script: |
        curl -u ${username}:${password} -X PUT "${repository}/$(chartName)-$(chartVersion).tgz" -T ./$(chartName)-$(chartVersion).tgz
      env:
        username: $(artifactory.helm.username)
        password: $(artifactory.helm.password)
        repository: $(artifactory.helm.url)
      displayName: Publish Chart
